// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace BlogWpfApp.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Blog
    {
        /// <summary>
        /// Initializes a new instance of the Blog class.
        /// </summary>
        public Blog() { }

        /// <summary>
        /// Initializes a new instance of the Blog class.
        /// </summary>
        public Blog(int? blogId = default(int?), string name = default(string), IList<Post> posts = default(IList<Post>))
        {
            BlogId = blogId;
            Name = name;
            Posts = posts;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BlogId")]
        public int? BlogId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Posts")]
        public IList<Post> Posts { get; set; }

    }
}
