// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace BlogWpfApp.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Post
    {
        /// <summary>
        /// Initializes a new instance of the Post class.
        /// </summary>
        public Post() { }

        /// <summary>
        /// Initializes a new instance of the Post class.
        /// </summary>
        public Post(int? postId = default(int?), string title = default(string), string content = default(string), int? blogId = default(int?), Blog blog = default(Blog))
        {
            PostId = postId;
            Title = title;
            Content = content;
            BlogId = blogId;
            Blog = blog;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PostId")]
        public int? PostId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Title")]
        public string Title { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Content")]
        public string Content { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BlogId")]
        public int? BlogId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Blog")]
        public Blog Blog { get; set; }

    }
}
